graph LR
    AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->SequelizeCoreModule
  AppModule-->SequelizeModule
  AppModule-->UsersModule
  ConfigHostModule-->ConfigModule
  ConfigHostModule-->SequelizeCoreModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->ConfigModule
  ConfigModule-->SequelizeCoreModule
  SequelizeCoreModule-->ConfigHostModule
  SequelizeCoreModule-->ConfigModule
  SequelizeModule-->ConfigHostModule
  SequelizeModule-->ConfigModule
  SequelizeModule-->SequelizeCoreModule
  UsersModule-->ConfigHostModule
  UsersModule-->ConfigModule
  UsersModule-->SequelizeCoreModule