graph LR
    AppModule-->AuthModule
  AppModule-->CategoriesModule
  AppModule-->ConfigHostModule
  AppModule-->ConfigModule
  AppModule-->MailerCoreModule
  AppModule-->MailerModule
  AppModule-->MaterialsModule
  AppModule-->ProductsModule
  AppModule-->SequelizeCoreModule
  AppModule-->SequelizeModule
  AppModule-->UsersModule
  AuthModule-->ConfigHostModule
  AuthModule-->ConfigModule
  AuthModule-->JwtModule
  AuthModule-->MailerCoreModule
  AuthModule-->PassportModule
  AuthModule-->SequelizeCoreModule
  AuthModule-->UsersModule
  CategoriesModule-->ConfigHostModule
  CategoriesModule-->ConfigModule
  CategoriesModule-->MailerCoreModule
  CategoriesModule-->ProductsModule
  CategoriesModule-->SequelizeCoreModule
  CategoriesModule-->SequelizeModule
  ConfigHostModule-->ConfigModule
  ConfigHostModule-->MailerCoreModule
  ConfigHostModule-->SequelizeCoreModule
  ConfigModule-->ConfigHostModule
  ConfigModule-->ConfigModule
  ConfigModule-->MailerCoreModule
  ConfigModule-->SequelizeCoreModule
  JwtModule-->ConfigHostModule
  JwtModule-->ConfigModule
  JwtModule-->MailerCoreModule
  JwtModule-->SequelizeCoreModule
  MailerCoreModule-->ConfigHostModule
  MailerCoreModule-->ConfigModule
  MailerCoreModule-->SequelizeCoreModule
  MailerModule-->ConfigHostModule
  MailerModule-->ConfigModule
  MailerModule-->MailerCoreModule
  MailerModule-->SequelizeCoreModule
  MaterialsModule-->ConfigHostModule
  MaterialsModule-->ConfigModule
  MaterialsModule-->MailerCoreModule
  MaterialsModule-->SequelizeCoreModule
  MaterialsModule-->SequelizeModule
  PassportModule-->ConfigHostModule
  PassportModule-->ConfigModule
  PassportModule-->MailerCoreModule
  PassportModule-->SequelizeCoreModule
  ProductsModule-->ConfigHostModule
  ProductsModule-->ConfigModule
  ProductsModule-->MailerCoreModule
  ProductsModule-->SequelizeCoreModule
  ProductsModule-->SequelizeModule
  SequelizeCoreModule-->ConfigHostModule
  SequelizeCoreModule-->ConfigModule
  SequelizeCoreModule-->MailerCoreModule
  SequelizeModule-->ConfigHostModule
  SequelizeModule-->ConfigModule
  SequelizeModule-->MailerCoreModule
  SequelizeModule-->SequelizeCoreModule
  UsersModule-->ConfigHostModule
  UsersModule-->ConfigModule
  UsersModule-->MailerCoreModule
  UsersModule-->SequelizeCoreModule
  UsersModule-->SequelizeModule