name: Deploy to Render

on:
    push:
        branches:
            - main
            - dev
            - KAFI-3/KAFI-35
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/kafi-server:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/kafi-server:${{ github.sha }}
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Render
              env:
                  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
                  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
              run: |
                  curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
                  -H "accept: application/json" \
                  -H "authorization: Bearer $RENDER_API_KEY"
services:
    - type: web
      name: kafi-server
      env: docker
      region: singapore
      plan: starter
      branch: main
      dockerfilePath: ./Dockerfile
      numInstances: 1
      healthCheckPath: /
      envVars:
          - key: NODE_ENV
            value: production
          - key: DATABASE
            sync: false # External PostgreSQL host
          - key: DB_PORT
            sync: false
          - key: DB_USERNAME
            sync: false
          - key: DB_PASSWORD
            sync: false
          - key: DB_NAME
            sync: false
          - key: REDIS_HOST
            sync: false # External Redis host
          - key: REDIS_PORT
            sync: false
          - key: REDIS_USER
            sync: false
          - key: REDIS_PASSWORD
            sync: false
          - key: AT_SECRET
            sync: false
          - key: RT_SECRET
            sync: false
          - key: SERVER_PORT
            value: 8080
