name: Run unit tests & coverage

on:
    push:
        branches: ['main', 'dev']
    pull_request:
        branches: ['main', 'dev']
        paths-ignore:
            - 'README.md'
            - 'LICENSE'
permissions:
    contents: write

jobs:
    unit-test:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '22'

            - name: Install dependencies
              run: pnpm install

            - name: Start pipeline
              run: timeout 10s pnpm run start:dev || true

            - name: Run unit tests (with Jest)
              run: pnpm test

            - name: Run test coverage (with Jest)
              run: pnpm test:cov

            - name: Install jq and bc
              run: |
                  sudo apt-get update
                  sudo apt-get install -y jq bc

            - name: Display test coverage summary
              run: cat coverage/coverage-summary.json | jq .

            - name: Check coverage threshold (50% lines)
              run: |
                  COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
                  echo "Line coverage: $COVERAGE%"
                  if (( $(echo "$COVERAGE < 50" | bc -l) )); then
                    echo "Coverage is below threshold of 50%!"
                    exit 1
                  else
                    echo "Coverage meets threshold."
                  fi
                  mv coverage/lcov-report coverage_report

            - name: Upload Coverage Report as Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: coverage_report
                  path: coverage_report

    deploy:
        needs: unit-test
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Download Coverage Report Artifact
              uses: actions/download-artifact@v4
              with:
                  name: coverage_report
                  path: coverage_report

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: coverage_report
                  clean: true
